"use client";

import * as React from "react";
import { motion, AnimatePresence, useInView } from "framer-motion";
import { Plus } from "lucide-react";
import { cn } from "@/lib/utils";

// --- FAQ Item Configuration ---
const FAQS = [
  {
    question: "How does the document AI understand context?",
    answer: "Our engine uses advanced Retrieval-Augmented Generation (RAG). Instead of matching basic keywords, it translates your entire document repository into multi-dimensional vectors, allowing the AI to understand semantic relationships and context across hundreds of pages.",
  },
  {
    question: "Is my corporate data secure and private?",
    answer: "Absolutely. We employ SOC-2 compliant isolated storage models and AES-256 bit encryption at rest. Your uploads are private to your session, stored securely, and completely excluded from generic public LLM training datasets.",
  },
  {
    question: "What file formats do you officially support?",
    answer: "We support a wide array of document structures including PDF, DOCX, CSV, XLSX, PPTX, TXT, and raw Markdown (.md) files. The maximum size per individual file upload is currently 120MB.",
  },
  {
    question: "Does the AI provide verifiable references?",
    answer: "Yes, precision is our priority. Every single claim, summary point, or answer generated by the assistant attaches a direct citation marker pointing directly to the specific page, section, or table within your source files.",
  },
];

// --- Reusable Accordion Row Component ---
function FAQRow({ question, answer, isOpen, onToggle }: { question: string; answer: string; isOpen: boolean; onToggle: () => void }) {
  return (
    <div className="border-b border-border/40 py-4 w-full text-left">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between gap-4 py-2 group outline-none focus-visible:ring-1 focus-visible:ring-primary rounded-lg"
        aria-expanded={isOpen}
      >
        <span className={cn(
          "text-sm font-semibold tracking-tight transition-colors duration-200",
          isOpen ? "text-foreground" : "text-muted-foreground group-hover:text-foreground"
        )}>
          {question}
        </span>
        <motion.div
          animate={{ rotate: isOpen ? 135 : 0 }}
          transition={{ duration: 0.25, ease: "easeInOut" }}
          className="text-muted-foreground shrink-0"
        >
          <Plus className="h-4 w-4 stroke-[2]" />
        </motion.div>
      </button>
      
      <AnimatePresence initial={false}>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
            className="overflow-hidden"
          >
            <p className="text-xs sm:text-[13px] text-muted-foreground leading-relaxed pt-2 pb-3 max-w-3xl pr-4 font-normal">
              {answer}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// --- Main Structural Section View ---
export default function FAQSection() {
  const sectionRef = React.useRef(null);
  const isInView = useInView(sectionRef, { once: true, margin: "-100px" });
  const [openIndex, setOpenIndex] = React.useState<number | null>(null);

  return (
    <section 
      ref={sectionRef}
      className="w-full py-24 bg-background overflow-hidden flex flex-col items-center border-t border-border/40"
      aria-label="Frequently asked questions section"
    >
      <div className="w-full max-w-4xl mx-auto px-4 flex flex-col md:flex-row gap-12 md:gap-20">
        
        {/* Left Side Static Title Node Layer */}
        <div className="w-full md:w-72 text-left shrink-0">
          <motion.span 
            initial={{ opacity: 0, x: -5 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 0.4 }}
            className="text-xs font-semibold tracking-wider text-primary uppercase block mb-3"
          >
            Support Center
          </motion.span>
          <motion.h2 
            initial={{ opacity: 0, y: 10 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.5, delay: 0.05 }}
            className="text-3xl font-bold tracking-tight text-foreground leading-tight"
          >
            Frequently <br />
            Asked <br className="hidden md:inline" />
            Questions.
          </motion.h2>
        </div>

        {/* Right Side Accordion Interactive Stream Matrix */}
        <motion.div 
          initial={{ opacity: 0, y: 15 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6, delay: 0.15 }}
          className="flex-1 w-full"
        >
          {FAQS.map((faq, index) => (
            <FAQRow
              key={index}
              question={faq.question}
              answer={faq.answer}
              isOpen={openIndex === index}
              onToggle={() => setOpenIndex(openIndex === index ? null : index)}
            />
          ))}
        </motion.div>

      </div>
    </section>
  );
}
